package model.dao.daoentities;
// default package
// Generated Mar 9, 2021 2:30:22 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblproduct generated by hbm2java
 */
@Entity
@Table(name = "tblproduct", catalog = "crossfire_db")
public class Tblproduct implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private TblproductId id;
	private String productTitle;
	private Integer productVipIngameLevel;
	private Integer productVipNumber;
	private String productInfo;
	private String productVipIngameImage;
	private String productImage;
	private Integer productPrice;
	private String productUserAdd;
	private String productUserUpdate;
	private String productCreateDate;
	private String productUpdateDate;
	private int count;
	private Boolean productDeleteFlag;

	public Tblproduct() {
	}

	public Tblproduct(TblproductId id, String productTitle, String productInfo) {
		this.id = id;
		this.productTitle = productTitle;
		this.productInfo = productInfo;
	}

	public Tblproduct(TblproductId id, String productTitle, Integer productVipIngameLevel, Integer productVipNumber,
			String productInfo, String productVipIngameImage, String productImage, Integer productPrice,
			String productUserAdd, String productUserUpdate, String productCreateDate, String productUpdateDate,
			Boolean productDeleteFlag,int count) {
		this.id = id;
		this.productTitle = productTitle;
		this.productVipIngameLevel = productVipIngameLevel;
		this.productVipNumber = productVipNumber;
		this.productInfo = productInfo;
		this.productVipIngameImage = productVipIngameImage;
		this.productImage = productImage;
		this.productPrice = productPrice;
		this.productUserAdd = productUserAdd;
		this.productUserUpdate = productUserUpdate;
		this.productCreateDate = productCreateDate;
		this.productUpdateDate = productUpdateDate;
		this.productDeleteFlag = productDeleteFlag;
		this.count = count;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productCode", column = @Column(name = "PRODUCT_CODE", nullable = false, length = 10)),
			@AttributeOverride(name = "productImageId", column = @Column(name = "PRODUCT_IMAGE_ID", nullable = false)) })
	public TblproductId getId() {
		return this.id;
	}

	public void setId(TblproductId id) {
		this.id = id;
	}

	@Column(name = "PRODUCT_TITLE", nullable = false, length = 25)
	public String getProductTitle() {
		return this.productTitle;
	}

	public void setProductTitle(String productTitle) {
		this.productTitle = productTitle;
	}

	@Column(name = "PRODUCT_VIP_INGAME_LEVEL")
	public Integer getProductVipIngameLevel() {
		return this.productVipIngameLevel;
	}

	public void setProductVipIngameLevel(Integer productVipIngameLevel) {
		this.productVipIngameLevel = productVipIngameLevel;
	}

	@Column(name = "PRODUCT_VIP_NUMBER")
	public Integer getProductVipNumber() {
		return this.productVipNumber;
	}

	public void setProductVipNumber(Integer productVipNumber) {
		this.productVipNumber = productVipNumber;
	}

	@Column(name = "PRODUCT_INFO", nullable = false, length = 200)
	public String getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(String productInfo) {
		this.productInfo = productInfo;
	}

	@Column(name = "PRODUCT_VIP_INGAME_IMAGE", length = 200)
	public String getProductVipIngameImage() {
		return this.productVipIngameImage;
	}

	public void setProductVipIngameImage(String productVipIngameImage) {
		this.productVipIngameImage = productVipIngameImage;
	}

	@Column(name = "PRODUCT_IMAGE", length = 200)
	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	@Column(name = "PRODUCT_PRICE")
	public Integer getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(Integer productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "PRODUCT_USER_ADD", length = 15)
	public String getProductUserAdd() {
		return this.productUserAdd;
	}

	public void setProductUserAdd(String productUserAdd) {
		this.productUserAdd = productUserAdd;
	}

	@Column(name = "PRODUCT_USER_UPDATE", length = 15)
	public String getProductUserUpdate() {
		return this.productUserUpdate;
	}

	public void setProductUserUpdate(String productUserUpdate) {
		this.productUserUpdate = productUserUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRODUCT_CREATE_DATE", length = 19)
	public String getProductCreateDate() {
		return this.productCreateDate;
	}

	public void setProductCreateDate(String productCreateDate) {
		this.productCreateDate = productCreateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRODUCT_UPDATE_DATE", length = 19)
	public String getProductUpdateDate() {
		return this.productUpdateDate;
	}

	public void setProductUpdateDate(String productUpdateDate) {
		this.productUpdateDate = productUpdateDate;
	}

	@Column(name = "PRODUCT_DELETE_FLAG")
	public Boolean getProductDeleteFlag() {
		return this.productDeleteFlag;
	}

	public void setProductDeleteFlag(Boolean productDeleteFlag) {
		this.productDeleteFlag = productDeleteFlag;
	}

	@Column(name = "COUNT")
	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
