package model.dao.daoentities;
// default package
// Generated Mar 9, 2021 2:30:22 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblproductId generated by hbm2java
 */
@Embeddable
public class TblproductId implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private String productCode;
	private int productImageId;

	public TblproductId() {
	}

	public TblproductId(String productCode, int productImageId) {
		this.productCode = productCode;
		this.productImageId = productImageId;
	}

	@Column(name = "PRODUCT_CODE", nullable = false, length = 10)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "PRODUCT_IMAGE_ID", nullable = false)
	public int getProductImageId() {
		return this.productImageId;
	}

	public void setProductImageId(int productImageId) {
		this.productImageId = productImageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblproductId))
			return false;
		TblproductId castOther = (TblproductId) other;

		return ((this.getProductCode() == castOther.getProductCode()) || (this.getProductCode() != null
				&& castOther.getProductCode() != null && this.getProductCode().equals(castOther.getProductCode())))
				&& (this.getProductImageId() == castOther.getProductImageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
		result = 37 * result + this.getProductImageId();
		return result;
	}

}
