package model.dao.daoentities;
// default package
// Generated Mar 31, 2021 11:45:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbluserId generated by hbm2java
 */
@Embeddable
public class TbluserId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private String userName;

	public TbluserId() {
	}

	public TbluserId(int userId, String userName) {
		this.userId = userId;
		this.userName = userName;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", nullable = false, length = 15)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbluserId))
			return false;
		TbluserId castOther = (TbluserId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		return result;
	}

}
