package model.dao.daoentities;
// default package
// Generated Mar 9, 2021 2:30:22 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblwalletId generated by hbm2java
 */
@Embeddable
public class TblwalletId implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private int walletId;
	private String walletName;
	private String walletAcount;

	public TblwalletId() {
	}

	public TblwalletId(int walletId, String walletName, String walletAcount) {
		this.walletId = walletId;
		this.walletName = walletName;
		this.walletAcount = walletAcount;
	}

	@Column(name = "WALLET_ID", nullable = false)
	public int getWalletId() {
		return this.walletId;
	}

	public void setWalletId(int walletId) {
		this.walletId = walletId;
	}

	@Column(name = "WALLET_NAME", nullable = false, length = 20)
	public String getWalletName() {
		return this.walletName;
	}

	public void setWalletName(String walletName) {
		this.walletName = walletName;
	}

	@Column(name = "WALLET_ACOUNT", nullable = false, length = 15)
	public String getWalletAcount() {
		return this.walletAcount;
	}

	public void setWalletAcount(String walletAcount) {
		this.walletAcount = walletAcount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblwalletId))
			return false;
		TblwalletId castOther = (TblwalletId) other;

		return (this.getWalletId() == castOther.getWalletId())
				&& ((this.getWalletName() == castOther.getWalletName()) || (this.getWalletName() != null
						&& castOther.getWalletName() != null && this.getWalletName().equals(castOther.getWalletName())))
				&& ((this.getWalletAcount() == castOther.getWalletAcount())
						|| (this.getWalletAcount() != null && castOther.getWalletAcount() != null
								&& this.getWalletAcount().equals(castOther.getWalletAcount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWalletId();
		result = 37 * result + (getWalletName() == null ? 0 : this.getWalletName().hashCode());
		result = 37 * result + (getWalletAcount() == null ? 0 : this.getWalletAcount().hashCode());
		return result;
	}

}
