package model.dao.daoentities;
// default package
// Generated Mar 9, 2021 2:30:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblwallet generated by hbm2java
 */
@Entity
@Table(name = "tblwallet", catalog = "crossfire_db")
public class Tblwallet implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	private TblwalletId id;
	private String walletTitle;
	private String walletBranch;
	private String walletMaster;
	private String walletImage;
	private String walletUserAdd;
	private String walletUserUpdate;
	private Date walletCreateDate;
	private Date walletUpdateDate;
	private Boolean walletDeleteFlag;

	public Tblwallet() {
	}

	public Tblwallet(TblwalletId id, String walletTitle, String walletMaster, String walletImage) {
		this.id = id;
		this.walletTitle = walletTitle;
		this.walletMaster = walletMaster;
		this.walletImage = walletImage;
	}

	public Tblwallet(TblwalletId id, String walletTitle, String walletBranch, String walletMaster, String walletImage,
			String walletUserAdd, String walletUserUpdate, Date walletCreateDate, Date walletUpdateDate,
			Boolean walletDeleteFlag) {
		this.id = id;
		this.walletTitle = walletTitle;
		this.walletBranch = walletBranch;
		this.walletMaster = walletMaster;
		this.walletImage = walletImage;
		this.walletUserAdd = walletUserAdd;
		this.walletUserUpdate = walletUserUpdate;
		this.walletCreateDate = walletCreateDate;
		this.walletUpdateDate = walletUpdateDate;
		this.walletDeleteFlag = walletDeleteFlag;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "walletId", column = @Column(name = "WALLET_ID", nullable = false)),
			@AttributeOverride(name = "walletName", column = @Column(name = "WALLET_NAME", nullable = false, length = 20)),
			@AttributeOverride(name = "walletAcount", column = @Column(name = "WALLET_ACOUNT", nullable = false, length = 15)) })
	public TblwalletId getId() {
		return this.id;
	}

	public void setId(TblwalletId id) {
		this.id = id;
	}

	@Column(name = "WALLET_TITLE", nullable = false, length = 10)
	public String getWalletTitle() {
		return this.walletTitle;
	}

	public void setWalletTitle(String walletTitle) {
		this.walletTitle = walletTitle;
	}

	@Column(name = "WALLET_BRANCH", length = 200)
	public String getWalletBranch() {
		return this.walletBranch;
	}

	public void setWalletBranch(String walletBranch) {
		this.walletBranch = walletBranch;
	}

	@Column(name = "WALLET_MASTER", nullable = false, length = 20)
	public String getWalletMaster() {
		return this.walletMaster;
	}

	public void setWalletMaster(String walletMaster) {
		this.walletMaster = walletMaster;
	}

	@Column(name = "WALLET_IMAGE", nullable = false, length = 200)
	public String getWalletImage() {
		return this.walletImage;
	}

	public void setWalletImage(String walletImage) {
		this.walletImage = walletImage;
	}

	@Column(name = "WALLET_USER_ADD", length = 15)
	public String getWalletUserAdd() {
		return this.walletUserAdd;
	}

	public void setWalletUserAdd(String walletUserAdd) {
		this.walletUserAdd = walletUserAdd;
	}

	@Column(name = "WALLET_USER_UPDATE", length = 15)
	public String getWalletUserUpdate() {
		return this.walletUserUpdate;
	}

	public void setWalletUserUpdate(String walletUserUpdate) {
		this.walletUserUpdate = walletUserUpdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WALLET_CREATE_DATE", length = 19)
	public Date getWalletCreateDate() {
		return this.walletCreateDate;
	}

	public void setWalletCreateDate(Date walletCreateDate) {
		this.walletCreateDate = walletCreateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WALLET_UPDATE_DATE", length = 19)
	public Date getWalletUpdateDate() {
		return this.walletUpdateDate;
	}

	public void setWalletUpdateDate(Date walletUpdateDate) {
		this.walletUpdateDate = walletUpdateDate;
	}

	@Column(name = "WALLET_DELETE_FLAG")
	public Boolean getWalletDeleteFlag() {
		return this.walletDeleteFlag;
	}

	public void setWalletDeleteFlag(Boolean walletDeleteFlag) {
		this.walletDeleteFlag = walletDeleteFlag;
	}

}
